# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sync Next Branch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  rebase-next:
    name: Rebase next onto master
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        id: app-token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        with:
          app-id: ${{ secrets.RECYCLARR_APP_ID }}
          private-key: ${{ secrets.RECYCLARR_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Rebase next onto master
        run: |
          git config user.name "recyclarr[bot]"
          git config user.email "recyclarr[bot]@users.noreply.github.com"
          git checkout next
          git rebase master
          git push --force-with-lease origin next
