# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sync Next Branch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  rebase-next:
    name: Rebase next onto master
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.RECYCLARR_APP_ID }}
          private-key: ${{ secrets.RECYCLARR_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Rebase next onto master
        run: |
          git config user.name "recyclarr[bot]"
          git config user.email "recyclarr[bot]@users.noreply.github.com"
          git checkout next
          git rebase master
          git push --force-with-lease origin next
